#!/usr/bin/bash

TMP=download/!tmp
PL=download/pl
UK=download/uk

echo "Start"

rm "$TMP"/*
rm "$PL"/*
rm "$UK"/*
rm data/*
rm out/*
echo "Download"

# Wig 20

wget "http://bossa.pl/pub/ciagle/omega/omegacgl.zip" -O download/!tmp/bossa.zip
unzip download/!tmp/bossa.zip -d $TMP

cp "$TMP"/11BIT.txt $PL
cp "$TMP"/ABCDATA.txt $PL

cp "$TMP"/06MAGNA.txt    "$PL"/. # Magna Polonia
cp "$TMP"/08OCTAVA.txt   "$PL"/. # Octava
cp "$TMP"/11BIT.txt      "$PL"/. # 11 bit studios
cp "$TMP"/4FUNMEDIA.txt  "$PL"/. # 4Fun Media
cp "$TMP"/ABCDATA.txt    "$PL"/. # ABC Data
cp "$TMP"/ABMSOLID.txt   "$PL"/. # ABM Solid
cp "$TMP"/ABPL.txt       "$PL"/. # AB
cp "$TMP"/ACAUTOGAZ.txt  "$PL"/. # AC
cp "$TMP"/ACTION.txt     "$PL"/. # Action SA w restrukturyzacji
cp "$TMP"/ADIUVO.txt     "$PL"/. # Adiuvo Investments
cp "$TMP"/AGORA.txt      "$PL"/. # Agora
cp "$TMP"/AGROTON.txt    "$PL"/. # Agroton Public Limited
cp "$TMP"/AGROWILL.txt   "$PL"/. # AB Agrowill Group
cp "$TMP"/AILLERON.txt   "$PL"/. # Ailleron
cp "$TMP"/AIRWAY.txt     "$PL"/. # Airway Medix
cp "$TMP"/ALCHEMIA.txt   "$PL"/. # Alchemia
cp "$TMP"/ALIOR.txt      "$PL"/. # Alior Bank
cp "$TMP"/ALMA.txt       "$PL"/. # Alma Market
cp "$TMP"/ALTA.txt       "$PL"/. # Alta
cp "$TMP"/ALUMETAL.txt   "$PL"/. # Alumetal
cp "$TMP"/AMBRA.txt      "$PL"/. # Ambra
cp "$TMP"/AMICA.txt      "$PL"/. # AMICA Wronki
cp "$TMP"/AMREST.txt     "$PL"/. # AmRest Holdings SE
cp "$TMP"/APATOR.txt     "$PL"/. # Apator
cp "$TMP"/APLISENS.txt   "$PL"/. # Aplisens
cp "$TMP"/APLITT.txt     "$PL"/. # Aplitt
cp "$TMP"/APSENERGY.txt  "$PL"/. # APS Energia
cp "$TMP"/ARCTIC.txt     "$PL"/. # Arctic Paper
cp "$TMP"/ARTERIA.txt    "$PL"/. # Arteria
cp "$TMP"/ASBIS.txt      "$PL"/. # ASBISc Enterprises PLC
cp "$TMP"/ASMGROUP.txt   "$PL"/. # ASM Group
cp "$TMP"/ASSECOPOL.txt  "$PL"/. #
cp "$TMP"/ASTARTA.txt    "$PL"/. # Astarta Holding NV
cp "$TMP"/ATAL.txt       "$PL"/. # Atal
cp "$TMP"/ATENDE.txt     "$PL"/. # Atende
cp "$TMP"/ATLANTAPL.txt  "$PL"/. # Atlanta Poland
cp "$TMP"/ATLANTIS.txt   "$PL"/. # Atlantis
cp "$TMP"/ATLASEST.txt   "$PL"/. # Atlas Estates Limited
cp "$TMP"/ATM.txt        "$PL"/. # ATM
cp "$TMP"/ATREM.txt      "$PL"/. # Atrem
cp "$TMP"/AVIAAML.txt    "$PL"/. # AviaAM Leasing AB
cp "$TMP"/AVIASG.txt     "$PL"/. # Avia Solutions Group AB
cp "$TMP"/AWBUD.txt      "$PL"/. # AWBUD
cp "$TMP"/BBIDEV.txt     "$PL"/. # BBI Development
cp "$TMP"/BEDZIN.txt     "$PL"/. # Elektrocieplownia Bedzin
cp "$TMP"/BENEFIT.txt    "$PL"/. # Benefit Systems
cp "$TMP"/BEST.txt       "$PL"/. # Best
cp "$TMP"/BETACOM.txt    "$PL"/. # Betacom
cp "$TMP"/BGZBNPP.txt    "$PL"/. # Bank BGZ BNP Paribas
cp "$TMP"/BIOMEDLUB.txt  "$PL"/. # Biomed-Lublin Wytwornia Surowic i Szczepionek
cp "$TMP"/BIOTON.txt     "$PL"/. # Bioton
cp "$TMP"/BMPAG.txt      "$PL"/. # bmp Holding AG
cp "$TMP"/BOGDANKA.txt   "$PL"/. # Lubelski Wegiel Bogdanka
cp "$TMP"/BORYSZEW.txt   "$PL"/. # Boryszew
cp "$TMP"/BOS.txt        "$PL"/. # Bank Ochrony Srodowiska
cp "$TMP"/BOWIM.txt      "$PL"/. # Bowim
cp "$TMP"/BRASTER.txt    "$PL"/. # Braster
cp "$TMP"/BRIJU.txt      "$PL"/. # Briju
cp "$TMP"/BSCDRUK.txt    "$PL"/. # BSC Drukarnia Opakowan
cp "$TMP"/BUDIMEX.txt    "$PL"/. # Budimex
cp "$TMP"/BUMECH.txt     "$PL"/. # Bumech
cp "$TMP"/BYTOM.txt      "$PL"/. # Bytom
cp "$TMP"/BZWBK.txt      "$PL"/. # Bank Zachodni WBK
cp "$TMP"/CALATRAVA.txt  "$PL"/. # Calatrava Capital
cp "$TMP"/CAPITAL.txt    "$PL"/. # Capital Partners
cp "$TMP"/CCC.txt        "$PL"/. # CCC
cp "$TMP"/CDPROJEKT.txt  "$PL"/. # CD Projekt
cp "$TMP"/CEZ.txt        "$PL"/. # CEZ a.s.
cp "$TMP"/CFI.txt        "$PL"/. # CFI Holding
cp "$TMP"/CHEMOS.txt     "$PL"/. # Chemoservis-Dwory
cp "$TMP"/CIECH.txt      "$PL"/. # Ciech
cp "$TMP"/CIGAMES.txt    "$PL"/. # CI Games
cp "$TMP"/CNT.txt        "$PL"/. # Centrum Nowoczesnych Technologii
cp "$TMP"/COALENERG.txt  "$PL"/. # Coal Energy
cp "$TMP"/COGNOR.txt     "$PL"/. # Cognor
cp "$TMP"/COLIAN.txt     "$PL"/. # Colian Holding
cp "$TMP"/COMARCH.txt    "$PL"/. # Comarch
cp "$TMP"/COMP.txt       "$PL"/. # Comp
cp "$TMP"/CORMAY.txt     "$PL"/. # PZ Cormay
cp "$TMP"/CUBEITG.txt    "$PL"/. # CUBE.ITG
cp "$TMP"/CYFRPLSAT.txt  "$PL"/. # Cyfrowy Polsat
cp "$TMP"/DEBICA.txt     "$PL"/. # Firma Oponiarska Debica
cp "$TMP"/DECORA.txt     "$PL"/. # Decora
cp "$TMP"/DELKO.txt      "$PL"/. # Delko
cp "$TMP"/DGA.txt        "$PL"/. # DGA
cp "$TMP"/DOMDEV.txt     "$PL"/. # Dom Development
cp "$TMP"/DREWEX.txt     "$PL"/. # Drewex
cp "$TMP"/DROP.txt       "$PL"/. # Drop
cp "$TMP"/DROZAPOL.txt   "$PL"/. # Drozapol-Profil
cp "$TMP"/ECHO.txt       "$PL"/. # Echo Investment
cp "$TMP"/EDINVEST.txt   "$PL"/. # ED Invest
cp "$TMP"/EFEKT.txt      "$PL"/. # Korporacja Gospodarcza Efekt
cp "$TMP"/EKOEXPORT.txt  "$PL"/. # Eko Export
cp "$TMP"/ELBUDOWA.txt   "$PL"/. # Elektrobudowa
cp "$TMP"/ELEKTROTI.txt  "$PL"/. # Elektrotim
cp "$TMP"/ELEMENTAL.txt  "$PL"/. # Elemental Holding
cp "$TMP"/ELKOP.txt      "$PL"/. # Elkop
cp "$TMP"/EMCINSMED.txt  "$PL"/. # EMC Instytut Medyczny
cp "$TMP"/EMPERIA.txt    "$PL"/. # Emperia Holding
cp "$TMP"/ENAP.txt       "$PL"/. # ENERGOAPARATURA
cp "$TMP"/ENEA.txt       "$PL"/. # Enea
cp "$TMP"/ENELMED.txt    "$PL"/. # Centrum Medyczne Enel-Med
cp "$TMP"/ENERGA.txt     "$PL"/. # Energa
cp "$TMP"/ENERGOINS.txt  "$PL"/. # Energoinstal
cp "$TMP"/ERBUD.txt      "$PL"/. # Erbud
cp "$TMP"/ERG.txt        "$PL"/. # ERG
cp "$TMP"/ERGIS.txt      "$PL"/. # Ergis
cp "$TMP"/ESOTIQ.txt     "$PL"/. # Esotiq & Henderson
cp "$TMP"/ESSYSTEM.txt   "$PL"/. # ES-System
cp "$TMP"/ETFDAX.txt     "$PL"/. #
cp "$TMP"/ETFSP500.txt   "$PL"/. #
cp "$TMP"/ETFW20L.txt    "$PL"/. #
cp "$TMP"/EUCO.txt       "$PL"/. # Europejskie Centrum Odszkodowan
cp "$TMP"/EUROCASH.txt   "$PL"/. # Eurocash
cp "$TMP"/EUROTEL.txt    "$PL"/. # Eurotel
cp "$TMP"/FAM.txt        "$PL"/. # FAM Grupa Kapitalowa
cp "$TMP"/FAMUR.txt      "$PL"/. # Famur
cp "$TMP"/FARMACOL.txt   "$PL"/. # Farmacol
cp "$TMP"/FASING.txt     "$PL"/. # Fabryka Sprzetu i Narzedzi Gorniczych Fasing
cp "$TMP"/FASTFIN.txt    "$PL"/. # Fast Finance
cp "$TMP"/FEERUM.txt     "$PL"/. # Feerum
cp "$TMP"/FERRO.txt      "$PL"/. # Ferro
cp "$TMP"/FERRUM.txt     "$PL"/. # Ferrum
cp "$TMP"/FMG.txt        "$PL"/. # Financial Assets Management Group
cp "$TMP"/FON.txt        "$PL"/. # Fon
cp "$TMP"/FORTE.txt      "$PL"/. # Fabryki Mebli FORTE
cp "$TMP"/FORTUNA.txt    "$PL"/. # Fortuna Entertainment Group NV
cp "$TMP"/FOTA.txt       "$PL"/. # Fota SA w upadlosci ukladowej
cp "$TMP"/GETIN.txt      "$PL"/. # Getin Holding
cp "$TMP"/GINOROSSI.txt  "$PL"/. # Gino Rossi
cp "$TMP"/GLCOSMED.txt   "$PL"/. # Global Cosmed
cp "$TMP"/GORENJE.txt    "$PL"/. # Gorenje gospodinjski aparati d.d.
cp "$TMP"/GPW.txt        "$PL"/. # Gielda Papierow Wartosciowych w Warszawie
cp "$TMP"/GRAVITON.txt   "$PL"/. # Graviton Capital
cp "$TMP"/GROCLIN.txt    "$PL"/. # Groclin
cp "$TMP"/GRODNO.txt     "$PL"/. # Grodno
cp "$TMP"/GRUPAAZOTY.txt "$PL"/. # Grupa Azoty
cp "$TMP"/GTC.txt        "$PL"/. # Globe Trade Centre
cp "$TMP"/HANDLOWY.txt   "$PL"/. # Bank Handlowy w Warszawie
cp "$TMP"/HARPER.txt     "$PL"/. # Harper Hygienics
cp "$TMP"/HAWE.txt       "$PL"/. # Hawe
cp "$TMP"/HELIO.txt      "$PL"/. # Helio
cp "$TMP"/HERKULES.txt   "$PL"/. # Herkules
cp "$TMP"/HUBSTYLE.txt   "$PL"/. # HubStyle
cp "$TMP"/HYDROTOR.txt   "$PL"/. # Przedsiebiorstwo Hydrauliki Silowej Hydrotor
cp "$TMP"/HYPERION.txt   "$PL"/. # Hyperion
cp "$TMP"/IDEABANK.txt   "$PL"/. # Idea Bank
cp "$TMP"/IFSA.txt       "$PL"/. # Investment Friends
cp "$TMP"/IMCOMPANY.txt  "$PL"/. # Industrial Milk Company
cp "$TMP"/IMMOBILE.txt   "$PL"/. # Grupa Kapitalowa Immobile
cp "$TMP"/IMPEL.txt      "$PL"/. # Impel
cp "$TMP"/IMPERA.txt     "$PL"/. # Impera Capital
cp "$TMP"/IMPEXMET.txt   "$PL"/. # Impexmetal
cp "$TMP"/INC.txt        "$PL"/. # INC
cp "$TMP"/INDATA.txt     "$PL"/. # Indata
cp "$TMP"/INDYGO.txt     "$PL"/. # IndygoTech Minerals
cp "$TMP"/INDYKPOL.txt   "$PL"/. # Indykpol
cp "$TMP"/INGBSK.txt     "$PL"/. # ING Bank Slaski
cp "$TMP"/INPRO.txt      "$PL"/. # Inpro
cp "$TMP"/INSTALKRK.txt  "$PL"/. # Instal Krakow
cp "$TMP"/INTEGERPL.txt  "$PL"/. # Integer.pl
cp "$TMP"/INTERBUD.txt   "$PL"/. # Interbud-Lublin
cp "$TMP"/INTERCARS.txt  "$PL"/. # Inter Cars
cp "$TMP"/INTERFERI.txt  "$PL"/. # Interferie
cp "$TMP"/INTERSPPL.txt  "$PL"/. # Intersport  Polska
cp "$TMP"/INTROL.txt     "$PL"/. # Introl
cp "$TMP"/INVISTA.txt    "$PL"/. # Invista
cp "$TMP"/IPOPEMA.txt    "$PL"/. # Ipopema Securities
cp "$TMP"/IZOBLOK.txt    "$PL"/. # Izo-Blok
cp "$TMP"/IZOLACJA.txt   "$PL"/. # Izolacja Jarocin
cp "$TMP"/IZOSTAL.txt    "$PL"/. # Izostal
cp "$TMP"/JHMDEV.txt     "$PL"/. # JHM Development
cp "$TMP"/JSW.txt        "$PL"/. # Jastrzebska Spolka Weglowa
cp "$TMP"/JWCONSTR.txt   "$PL"/. # J.W. Construction Holding
cp "$TMP"/K2INTERNT.txt  "$PL"/. # K2 Internet
cp "$TMP"/KANIA.txt      "$PL"/. # Zaklady Miesne Henryk Kania
cp "$TMP"/KBDOM.txt      "$PL"/. # Korporacja Budowlana Dom
cp "$TMP"/KCI.txt        "$PL"/. # KCI
cp "$TMP"/KERDOS.txt     "$PL"/. # Kerdos Group SA w restrukturyzacji
cp "$TMP"/KERNEL.txt     "$PL"/. # Kernel Holding
cp "$TMP"/KETY.txt       "$PL"/. # Grupa Kety
cp "$TMP"/KGHM.txt       "$PL"/. # KGHM Polska Miedz
cp "$TMP"/KINOPOL.txt    "$PL"/. # Kino Polska TV
cp "$TMP"/KOGENERA.txt   "$PL"/. # Zespol Elektrocieplowni Wroclawskich Kogeneracja
cp "$TMP"/KOMPAP.txt     "$PL"/. # Przedsiebiorstwo Produkcyjno-Handlowe Kompap
cp "$TMP"/KOMPUTRON.txt  "$PL"/. # Komputronik
cp "$TMP"/KONSSTALI.txt  "$PL"/. # Konsorcjum Stali
cp "$TMP"/KOPEX.txt      "$PL"/. # KOPEX
cp "$TMP"/KRAKCHEM.txt   "$PL"/. # Krakchemia
cp "$TMP"/KREC.txt       "$PL"/. # Krynicki Recykling
cp "$TMP"/KREDYTIN.txt   "$PL"/. # Kredyt Inkaso
cp "$TMP"/KREZUS.txt     "$PL"/. # Krezus
cp "$TMP"/KRUK.txt       "$PL"/. # Kruk
cp "$TMP"/KRUSZWICA.txt  "$PL"/. # Zaklady Tluszczowe Kruszwica
cp "$TMP"/KSGAGRO.txt    "$PL"/. # KSG Agro
cp "$TMP"/LABOPRINT.txt  "$PL"/. # Labo Print
cp "$TMP"/LARK.txt       "$PL"/. # Lark.pl
cp "$TMP"/LARQ.txt       "$PL"/. # Larq
cp "$TMP"/LCCORP.txt     "$PL"/. # LC Corp
cp "$TMP"/LENA.txt       "$PL"/. # Lena Lighting
cp "$TMP"/LENTEX.txt     "$PL"/. # Lentex
cp "$TMP"/LIBET.txt      "$PL"/. # Libet
cp "$TMP"/LIVECHAT.txt   "$PL"/. # LiveChat Software
cp "$TMP"/LOTOS.txt      "$PL"/. # Grupa Lotos
cp "$TMP"/LPP.txt        "$PL"/. # LPP
cp "$TMP"/LSISOFT.txt    "$PL"/. # LSI Software
cp "$TMP"/LUBAWA.txt     "$PL"/. # LUBAWA
cp "$TMP"/MABION.txt     "$PL"/. # Mabion
cp "$TMP"/MAKARONPL.txt  "$PL"/. # Makarony Polskie
cp "$TMP"/MARVIPOL.txt   "$PL"/. # Marvipol
cp "$TMP"/MBANK.txt      "$PL"/. # mBank
cp "$TMP"/MBWS.txt       "$PL"/. # Marie Brizards Wine & Spirits
cp "$TMP"/MCI.txt        "$PL"/. # MCI Capital
cp "$TMP"/MCLOGIC.txt    "$PL"/. # Macrologic
cp "$TMP"/MDIENERGIA.txt "$PL"/. # MDI Energia
cp "$TMP"/MEDICALG.txt   "$PL"/. # Medicalgorithmics
cp "$TMP"/MENNICA.txt    "$PL"/. # Mennica Polska
cp "$TMP"/MERCATOR.txt   "$PL"/. # Mercator Medical
cp "$TMP"/MERCOR.txt     "$PL"/. # Mercor
cp "$TMP"/MEXPOLSKA.txt  "$PL"/. # Mex Polska
cp "$TMP"/MFO.txt        "$PL"/. # MFO
cp "$TMP"/MILKILAND.txt  "$PL"/. # Milkiland NV
cp "$TMP"/MILLENNIUM.txt "$PL"/. # Bank Millennium
cp "$TMP"/MIRACULUM.txt  "$PL"/. # Miraculum
cp "$TMP"/MIRBUD.txt     "$PL"/. # Mirbud
cp "$TMP"/MOL.txt        "$PL"/. # MOL Magyar Olaj
cp "$TMP"/MONNARI.txt    "$PL"/. # Monnari Trade
cp "$TMP"/MOSTALPLC.txt  "$PL"/. # MOSTOSTAL Plock
cp "$TMP"/MOSTALWAR.txt  "$PL"/. # Mostostal Warszawa
cp "$TMP"/MOSTALZAB.txt  "$PL"/. # Mostostal Zabrze
cp "$TMP"/MUZA.txt       "$PL"/. # MUZA
cp "$TMP"/NETIA.txt      "$PL"/. # Netia
cp "$TMP"/NETMEDIA.txt   "$PL"/. # Netmedia
cp "$TMP"/NEUCA.txt      "$PL"/. # Neuca
cp "$TMP"/NEWAG.txt      "$PL"/. # Newag
cp "$TMP"/NORTCOAST.txt  "$PL"/. # North Coast
cp "$TMP"/NOVITA.txt     "$PL"/. # NOVITA
cp "$TMP"/NOWAGALA.txt   "$PL"/. # Ceramika Nowa Gala
cp "$TMP"/NTTSYSTEM.txt  "$PL"/. # NTT System
cp "$TMP"/ODLEWNIE.txt   "$PL"/. # Odlewnie Polskie
cp "$TMP"/OEX.txt        "$PL"/. # OEX
cp "$TMP"/OPENFIN.txt    "$PL"/. # Open Finance
cp "$TMP"/OPONEO.PL.txt  "$PL"/. # Oponeo.pl
cp "$TMP"/OPTEAM.txt     "$PL"/. # OPTeam
cp "$TMP"/ORANGEPL.txt   "$PL"/. # Orange Polska
cp "$TMP"/ORBIS.txt      "$PL"/. # Orbis
cp "$TMP"/ORCOGROUP.txt  "$PL"/. # Orco Property Group
cp "$TMP"/ORION.txt      "$PL"/. # Orion Investment
cp "$TMP"/ORZBIALY.txt   "$PL"/. # Orzel Bialy
cp "$TMP"/OTLOG.txt      "$PL"/. # OT Logistics
cp "$TMP"/OVOSTAR.txt    "$PL"/. # Ovostar Union N.V.
cp "$TMP"/PAGED.txt      "$PL"/. # Paged
cp "$TMP"/PAMAPOL.txt    "$PL"/. # Pamapol
cp "$TMP"/PANOVA.txt     "$PL"/. # P.A. Nova
cp "$TMP"/PBG.txt        "$PL"/. # PBG
cp "$TMP"/PBSFINANSE.txt "$PL"/. # PBS Finanse
cp "$TMP"/PEKAO.txt      "$PL"/. # Bank Polska Kasa Opieki
cp "$TMP"/PELION.txt     "$PL"/. # Pelion
cp "$TMP"/PEP.txt        "$PL"/. # Polenergia
cp "$TMP"/PEPEES.txt     "$PL"/. # Przedsiebiorstwo Przemyslu Spozywczego PEPEES
cp "$TMP"/PGE.txt        "$PL"/. # PGE Polska Grupa Energetyczna
cp "$TMP"/PGNIG.txt      "$PL"/. # Polskie Gornictwo Naftowe i Gazownictwo
cp "$TMP"/PGODLEW.txt    "$PL"/. # Polska Grupa Odlewnicza
cp "$TMP"/PGSSOFT.txt    "$PL"/. # PGS Software
cp "$TMP"/PHN.txt        "$PL"/. # Polski Holding Nieruchomosci
cp "$TMP"/PKNORLEN.txt   "$PL"/. # Polski Koncern Naftowy Orlen
cp "$TMP"/PKOBP.txt      "$PL"/. # Powszechna Kasa Oszczednosci Bank Polski
cp "$TMP"/PLASTBOX.txt   "$PL"/. # Przetworstwo Tworzyw Sztucznych Plast-Box
cp "$TMP"/PLATYNINW.txt  "$PL"/. # Platynowe Inwestycje
cp "$TMP"/PMPG.txt       "$PL"/. # PMPG Polskie Media
cp "$TMP"/POLICE.txt     "$PL"/. # Grupa Azoty Zaklady Chemiczne Police
cp "$TMP"/POLIMEXMS.txt  "$PL"/. # Polimex-Mostostal
cp "$TMP"/POLMED.txt     "$PL"/. # Polmed
cp "$TMP"/POLNA.txt      "$PL"/. # Zaklady Automatyki POLNA
cp "$TMP"/POLNORD.txt    "$PL"/. # Polnord
cp "$TMP"/POZBUD.txt     "$PL"/. # Pozbud T&R
cp "$TMP"/PRAGMAFA.txt   "$PL"/. # Pragma Faktoring
cp "$TMP"/PRAGMAINK.txt  "$PL"/. # Pragma Inkaso
cp "$TMP"/PRIMAMODA.txt  "$PL"/. # Prima Moda
cp "$TMP"/PROCAD.txt     "$PL"/. # Procad
cp "$TMP"/PROCHEM.txt    "$PL"/. # Prochem
cp "$TMP"/PROCHNIK.txt   "$PL"/. # Prochnik
cp "$TMP"/PROJPRZEM.txt  "$PL"/. # PROJPRZEM
cp "$TMP"/PROTEKTOR.txt  "$PL"/. # Protektor
cp "$TMP"/PULAWY.txt     "$PL"/. # Grupa Azoty Zaklady Azotowe Pulawy
cp "$TMP"/PWRMEDIA.txt   "$PL"/. # Power Media
cp "$TMP"/PZU.txt        "$PL"/. # Powszechny Zaklad Ubezpieczen
cp "$TMP"/QUANTUM.txt    "$PL"/. # Quantum Software
cp "$TMP"/QUERCUS.txt    "$PL"/. # Quercus Towarzystwo Funduszy Inwestycyjnych
cp "$TMP"/QUMAK.txt      "$PL"/. # Qumak
cp "$TMP"/RADPOL.txt     "$PL"/. # Radpol
cp "$TMP"/RAFAKO.txt     "$PL"/. # RAFAKO
cp "$TMP"/RAFAMET.txt    "$PL"/. # Fabryka Obrabiarek RAFAMET
cp "$TMP"/RAINBOW.txt    "$PL"/. # Rainbow Tours
cp "$TMP"/RANKPROGR.txt  "$PL"/. # Rank Progress
cp "$TMP"/RAWLPLUG.txt   "$PL"/. # Rawlplug
cp "$TMP"/RCCRUAOPEN.txt "$PL"/. #
cp "$TMP"/RCGLDAOPEN.txt "$PL"/. #
cp "$TMP"/REDAN.txt      "$PL"/. # Redan
cp "$TMP"/REDWOOD.txt    "$PL"/. # Redwood Holding
cp "$TMP"/RELPOL.txt     "$PL"/. # Relpol
cp "$TMP"/REMAK.txt      "$PL"/. # Przedsiebiorstwo Modernizacji Urzadzen Energetycznych REMAK
cp "$TMP"/RESBUD.txt     "$PL"/. # Resbud
cp "$TMP"/ROBYG.txt      "$PL"/. # Robyg
cp "$TMP"/RONSON.txt     "$PL"/. # Ronson Europe N.V.
cp "$TMP"/ROPCZYCE.txt   "$PL"/. # Zaklady Magnezytowe Ropczyce
cp "$TMP"/RUBICON.txt    "$PL"/. # Rubicon Partners
cp "$TMP"/SADOVAYA.txt   "$PL"/. # Sadovaya Group
cp "$TMP"/SANOK.txt      "$PL"/. # Sanok Rubber Company
cp "$TMP"/SANWIL.txt     "$PL"/. # Sanwil Holding
cp "$TMP"/SECOGROUP.txt  "$PL"/. # Seco/Warwick
cp "$TMP"/SEKO.txt       "$PL"/. # Seko
cp "$TMP"/SELVITA.txt    "$PL"/. # Selvita
cp "$TMP"/SFINKS.txt     "$PL"/. # Sfinks Polska
cp "$TMP"/SILVANO.txt    "$PL"/. # Silvano Fashion Group AS
cp "$TMP"/SIMPLE.txt     "$PL"/. # SIMPLE
cp "$TMP"/SKOTAN.txt     "$PL"/. # SKOTAN
cp "$TMP"/SKYLINE.txt    "$PL"/. # Skyline Investment
cp "$TMP"/SNIEZKA.txt    "$PL"/. # Fabryka Farb i Lakierow Sniezka
cp "$TMP"/SOHODEV.txt    "$PL"/. # Soho Development
cp "$TMP"/SOLAR.txt      "$PL"/. # SOLAR Company
cp "$TMP"/SONEL.txt      "$PL"/. # Sonel
cp "$TMP"/STALEXP.txt    "$PL"/. # Stalexport Autostrady
cp "$TMP"/STALPROD.txt   "$PL"/. # Stalprodukt
cp "$TMP"/STALPROFI.txt  "$PL"/. # STALPROFIL
cp "$TMP"/STAPORKOW.txt  "$PL"/. # Zaklady Urzadzen Kotlowych Staporkow
cp "$TMP"/STARHEDGE.txt  "$PL"/. # Starhedge
cp "$TMP"/SUWARY.txt     "$PL"/. # Suwary
cp "$TMP"/SWISSMED.txt   "$PL"/. # Swissmed Centrum Zdrowia
cp "$TMP"/SYGNITY.txt    "$PL"/. # Sygnity
cp "$TMP"/SYNEKTIK.txt   "$PL"/. # Synektik
cp "$TMP"/SYNTHOS.txt    "$PL"/. # Synthos
cp "$TMP"/TALEX.txt      "$PL"/. # Talex
cp "$TMP"/TARCZYNSKI.txt "$PL"/. # Tarczynski
cp "$TMP"/TATRY.txt      "$PL"/. # Tatry Mountain Resorts AS
cp "$TMP"/TAURONPE.txt   "$PL"/. # Tauron Polska Energia
cp "$TMP"/TERMOREX.txt   "$PL"/. # Termo-Rex
cp "$TMP"/TESGAS.txt     "$PL"/. # Tesgas
cp "$TMP"/TFONE.txt      "$PL"/. # TelForceOne
cp "$TMP"/TIM.txt        "$PL"/. # TIM
cp "$TMP"/TOPMEDICA.txt  "$PL"/. # Topmedical
cp "$TMP"/TORPOL.txt     "$PL"/. # Torpol
cp "$TMP"/TRAKCJA.txt    "$PL"/. # Trakcja PRKiI
cp "$TMP"/TRANSPOL.txt   "$PL"/. # Trans Polonia
cp "$TMP"/TRITON.txt     "$PL"/. # Triton Development
cp "$TMP"/ULMA.txt       "$PL"/. # ULMA Construccion Polska
cp "$TMP"/UNIBEP.txt     "$PL"/. # Unibep
cp "$TMP"/UNICREDIT.txt  "$PL"/. # UniCredit S.p.A.
cp "$TMP"/UNIMA.txt      "$PL"/. # Unima 2000 Systemy Teleinformatyczne
cp "$TMP"/UNIWHEELS.txt  "$PL"/. # Uniwheels AG
cp "$TMP"/URSUS.txt      "$PL"/. # Ursus
cp "$TMP"/VANTAGE.txt    "$PL"/. # Vantage Development
cp "$TMP"/VINDEXUS.txt   "$PL"/. # Gielda Praw Majatkowych Vindexus
cp "$TMP"/VISTAL.txt     "$PL"/. # Vistal Gdynia
cp "$TMP"/VISTULA.txt    "$PL"/. # Vistula Group
cp "$TMP"/VOTUM.txt      "$PL"/. # Votum
cp "$TMP"/VOXEL.txt      "$PL"/. # Voxel
cp "$TMP"/WADEX.txt      "$PL"/. # Przedsiebiorstwo Produkcyjno Handlowe Wadex
cp "$TMP"/WARIMPEX.txt   "$PL"/. # Warimpex Finanz & und Beteiligungs AG
cp "$TMP"/WASKO.txt      "$PL"/. # Wasko
cp "$TMP"/WAWEL.txt      "$PL"/. # WAWEL
cp "$TMP"/WDX.txt        "$PL"/. # WDX
cp "$TMP"/WIELTON.txt    "$PL"/. # Wielton

echo "Python"
#./dane_BOSSA.py
#./gieldomat.py
./ichi.py

rm "$TMP"/*

#less out/raport.txt
